import React from 'react';
import '../styles/main.scss';
import type { Metadata } from 'next';
import { Archivo } from 'next/font/google';

const archivo = Archivo({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Tech in Lar',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt_BR">
      <body className={archivo.className}>{children}</body>
    </html>
  );
}
